- name: installing redis database
  hosts: redis_servers
  become: yes
  tasks:
  - name: disable default redis
    ansible.builtin.command: "dnf module disable redis -y"

  - name: enable redis 7 version
    ansible.builtin.command: dnf module enable redis:7 -y