- name: Installing shipping component for Roboshop project
  hosts: shipping_servers
  become: yes
  tasks:
  - name: installing maven 
    ansible.builtin.dnf:
      name: maven
      state: installed 

  - name: create user for roboshop project 
    ansible.builtin.user:
      name: roboshop
      state: present
      comment: "roboshop system user"
      home: /app
      shell: /bin/bash

  - name: create app directory 
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download catalogue content
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /app
      remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  