- name: Installing shipping component for Roboshop project
  hosts: shipping_servers
  become: yes
  tasks:
  - name: installing maven 
    ansible.builtin.dnf:
      name: maven
      state: installed 

  - name: create user for roboshop project 
    ansible.builtin.user:
      name: roboshop
      state: present
      comment: "roboshop system user"
      home: /app
      shell: /bin/bash

  - name: create app directory 
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download catalogue content
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /app
      remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service file
    ansible.builtin.copy:
      src: 08-shipping.service
      dest: /etc/systemd/system/shipping.service

  - name:  daemon realod , enabled and start the service 
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: shipping
      state: started
      enabled: true

  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: Load the schema into database
    community.mysql.mysql_db:
      name: all
      login_host: mysql.naveenrajoli.site
      login_user: root
      login_password: RoboShop@1
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name:  daemon realod , enabled and start the service 
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: shipping
      state: started
  
