- name: Installing dispatch component for Roboshop project
  hosts: dispatch_servers
  become: yes
  tasks:
  - name: installing golang
    ansible.builtin.dnf:
      name: golang
      state: installed 

  - name: create user for roboshop project 
    ansible.builtin.user:
      name: roboshop
      state: present
      comment: "roboshop system user"
      home: /app
      shell: /bin/bash

  - name: create app directory 
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download catalogue content
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /app
      remote_src: yes

  - name: Initialize Go module
    ansible.builtin.shell: go mod init dispatch
    args:
      chdir: /app
      
  - name: Download Go dependencies
    ansible.builtin.shell: go get
    args:
      chdir: /app

  - name: Build Go project
    ansible.builtin.shell: go build
    args:
      chdir: /app

  - name: copy dispatch service file
    ansible.builtin.copy:
      src: 10-dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name:  daemon realod , enabled and start the service 
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: dispatch
      state: started
      enabled: true
