- name: Installing Gmail setup to redirect the logs
  hosts: dispatch_servers
  become: yes
  tasks:
  - name: installing  Postfix, the SASL authentication framework, and mailx.
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed 
    loop:
    - postfix
    - cyrus-sasl-plain
    - mutt

  - name: start postfix service
    ansible.builtin.service:
      name: postfix
      state: started
      enabled: true

  - name: Configure postfix relay settings
    ansible.builtin.blockinfile:
      path: /etc/postfix/main.cf
      block: |
        relayhost = [smtp.gmail.com]:587
        smtp_use_tls = yes
        smtp_sasl_auth_enable = yes
        smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
        smtp_sasl_security_options = noanonymous
        smtp_sasl_tls_security_options = noanonymous
        smtpd_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
      marker: "# {mark} POSTFIX RELAY SETTINGS"
      create: yes
    become: true

      
  - name: Create and add Gmail SMTP credentials to sasl_passwd
    ansible.builtin.lineinfile:
      path: /etc/postfix/sasl_passwd
      line: "[smtp.gmail.com]:587 keerthirajoli04@gmail.com:szpkcivtzsxetmmu"
      create: yes
      state: present
      
  - name: Create a Postfix lookup table from the sasl_passwd
    ansible.builtin.command: postmap /etc/postfix/sasl_passwd

  - name: Add legacy provider in openssl.cnf under [provider_sect]
    ansible.builtin.blockinfile:
      path: /etc/ssl/openssl.cnf
      marker: "; ANSIBLE MANAGED BLOCK: legacy provider"
      insertafter: '^\[provider_sect\]'
      block: |
        legacy = legacy

  - name: send mailx
    ansible.builtin.shell: "echo 'This is a test mail & Date $(date)' | mutt -s 'message' naveenrajoli@gmail.com"

      
      
      
      
      
      
      
      
      
    
