- name: Installing Gmail setup to redirect the logs
  hosts: dispatch_servers
  become: yes
  tasks:
  - name: installing  Postfix, the SASL authentication framework, and mailx.
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed 
    loop:
    - postfix
    - cyrus-sasl-plain
    - mutt

  - name: start postfix service
    ansible.builtin.service:
      name: postfix
      state: started
      enabled: true